name: Testing

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies (if needed)
        run: sudo apt-get update && sudo apt-get install -y make bash

      - name: Run Make Create
        run: ls && bash -c 'source ./.devcontainer/setup.sh' >> ./.devcontainer/postCreate.log 2>&1'
